theme = 'hugo-theme-learn'

[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
  themeVariant = "workshop"
  showVisitedLinks = true
  disableLandingPageButton = true 
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Build and deploy 1 fullstack web app using amplify gen 2 and angular"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "Build và deploy 1 fullstack web app sử dụng amplify gen 2 và angular"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 21
